name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # 120+30 day stale policy for PRs
      # * Except PRs marked as "no stale"
      - name: Stale PRs policy
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-pr-labels: "no stale"
          days-before-stale: 120
          days-before-close: 30
          days-before-issue-stale: -1
          days-before-issue-close: -1
          remove-stale-when-updated: true
          stale-pr-label: "stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. It has been
            automatically marked as stale because of that and it will be closed if no
            further activity occurs in the next 30 days.

      # 60+30 day stale policy for issues pending more information
      # * Issues that are pending more information
      # * Except Issues marked as "no stale"
      - name: Needs more information stale issues policy
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: "needs more information"
          exempt-issue-labels: "no stale"
          days-before-stale: 60
          days-before-close: 30
          days-before-pr-stale: -1
          days-before-pr-close: -1
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          stale-issue-message: >
            This issue needs more information and there hasn't been any activity for the
            past 60 days. It will be automatically closed in 30 days unless there's some
            activity.
